bugsnag/bugsnag-go

- README.md
- event.go
I guess this pull request solves https://github.com/bugsnag/bugsnag-go/issues/17.
As ConradIrwin says, just using the error message is too unique. So I added an option to configure ErrorClass like [bugsnag-node's errorName](https://github.com/bugsnag/bugsnag-node#errorname).
> Added an option to override error class.

- notifier.go
- payload.go
The current implementation will swallow any delivery errors that run in a goroutine (the default behaviour). This PR changes the goroutine to call `deliverOrLog` which will at least log any errors which occur. We spent a fair amount of time debugging why errors were not being notified only to find that we didn't have any SSL Certificates in our Docker image, and bugsnag was unable to connect. Due to the lack of any error reporting, this was a bit of a rabbit-hole to figure out.
> Don't swallow errors in a goroutine

- bugsnag_test.go
- middleware.go
This changes the notifier to use a lowercase "request" and "url" in the metadata. This means that Bugsnag will allow filtering by URL for Go notifications.
> Lowercase request map

- errors/error.go
This allows the creation of error objects other than bugsnag.Error that have stack-traces.
The use case for us is making errors that are Retryable and also have the right stack trace: https://github.com/codeship/go-retro
Now I have more experience with go, I'd probably have written this library to use an interface type rather than a struct type from the start; but this is a backward compatible addition.
> Add ErrorWithCallers interface

- errors/error.go
- errors/error_test.go
`Error.stack` is rebuilt from the stack frames' program counter, `Error.frames` is set by calling a `StackFrames` method.
Fixes #43.
> Add support for errors with stack outside of original runtime

- metadata.go
- metadata_test.go
Given a nil pointer value, sanitizer.Sanitize panics when trying to call
Elem().Interface() on it. Fix by checking for nil pointer before trying
to retreive the underlying value.
> Mend nil-pointer panic

- bugsnag.go
- examples/using-goroutines/main.go
- notifier.go
- panicwrap_test.go
When an unhandled panic occurs in a goroutine and the configuration specifies that error reports are delivered to bugsnag asynchronously, there is the potential for the crash and cleanup to occur before the report is sent. 
This change specifies that panics captured via `AutoNotify` are delivered synchronously before repanicking, ensuring that delivery occurs before shutdown. It also includes some small improvements to the documentation and an addition to the examples for using the library within goroutines.
To accompany this change will be a new section of the Go integration guide on docs.bugsnag.com on panic handling in goroutines.
Fixes #47
> Improve goroutine handling

- examples/README.md
- examples/appengine/README.md
- examples/appengine/hello.go
- examples/gin/main.go
- examples/http/main.go
- examples/revelapp/README.md
The examples are somewhat in disarray at the moment, this change brings them into line as being somewhat similarly configured and adds a landing README for explaining what each one does.
Somewhat dependent on #52 (for the goroutine example)
> Cleanup example documentation, create landing

- bugsnag.go
- configuration.go
- configuration_test.go
- examples/gin/main.go
- examples/gin/request.go
The file name component of a stack frame on bugsnag resolves to the full path at which a binary is built for any file which is not the entry point of the application. For example, building the gin example in commit 8e66a5f results in a path similar to:
```
/Users/[username]/path/to/go/code/src/github.com/bugsnag/bugsnag-go/examples/gin/request.go:31
``` 
The expected default is
```
github.com/bugsnag/bugsnag-go/examples/gin/request.go:31
```
Which can then be trimmed using the `ProjectPackages` option to 
```
request.go:31
```
Because of this problem, the same bug manifesting in two versions of a Go application built on two different machines resolves different stack frames when generating Bugsnag error reports.
This changeset updates an example to demonstrate the problem and adds a …
> fix: Strip GOPATH from callstack frame file paths

- revel/bugsnagrevel.go
Hello, 
Revel introduced breaking changes with v0.18.0 - [Changelog](https://github.com/revel/revel/blob/master/CHANGELOG.md). 
> http.Request is no longer contained in revel.Request revel.Request remains functionally the same but you cannot extract the http.Request from it. You can get the http.Request from revel.Controller.Request.In.GetRaw().(*http.Request)
> Support Revel release v0.18.0

- bugsnag.go
- bugsnag_test.go
- configuration.go
- configuration_test.go
- headers.go
- headers_test.go
- panicwrap_test.go
- payload.go
- revel/bugsnagrevel.go
- session.go
- session_test.go
- tests/fixtures/gin.go
- tests/fixtures/martini.go
- tests/fixtures/negroni.go
- tests/fixtures/revel/app/init.go
- tests/utils.go
In order to add session tracking to this notifier we need to be able to send the session payloads to session.bugsnag.com. This change establishes that logic along with the necessary configuration updates.
There now exists a non-exported `deliverSessions()` function that is intended to be called at regular intervals which will publish the provided sessions. It may be reasonable to make this function into a method in the future for additional testability, but it is currently left as simple as possible, i.e. no receiver.
The configuration parameter `Endpoint` has now been deprecated in favour of `Endpoints` - an analogous change to what has been made to other platforms.
- `Configuration.Endpoints` which relies on the `Endpoints` struct where you can specify the `Notify` and `Sessions` …
> Session tracking delivery logic

- CHANGELOG.md
- bugsnag.go
- panicwrap.go
Due to a bug in the existing `notifier.NotifySync` method, we end up
using the notifier's config value to determine whether to send
synchronously or async. In the case of a fatal panic (i.e not
`AutoNotified` or `Recover`-ed) it still got sent asynchronously.
This change ensures that it does get sent synchronously.
Tested by putting a panic immediately after the Bugsnag configuration, and seeing if it got reported.
> [fix] Ensure fatal panics are notified

- Makefile
- bugsnag.go
- bugsnag_test.go
- configuration.go
- event.go
- event_test.go
- gin/bugsnaggin.go
- gin/gin_test.go
- martini/bugsnagmiddleware.go
- martini/martini_test.go
- metadata.go
- metadata_test.go
- middleware.go
- negroni/bugsnagnegroni.go
- negroni/negroni_test.go
- panicwrap_test.go
- payload.go
- report.go
- request_extractor.go
- request_extractor_test.go
- revel/bugsnagrevel.go
- revel/request_extractor.go
- revel/request_extractor_test.go
- testutil/json.go
Putting the `http.Request` object in the context (of the request - meta, I know) so that we can take it out when a `context.Context` is passed to `bugsnag.Notify` and get request information in the dashboard with minimal effort. Attempts to extract all the properties mentioned in the notify API.
> Request data in context

- bugsnag.go
- bugsnag_example_test.go
- bugsnag_test.go
- event.go
- gin/gin_test.go
- martini/martini_test.go
- negroni/negroni_test.go
- notifier.go
- notifier_test.go
- report_publisher.go
- testutil/json.go
This reverts a previous change that was made to make the go notifier a bit more idiomatic. However, we don't intend on making the addition of session tracking a major release, semver-ily speaking, and this is strictly speaking a breaking change.
The change of signature from
```go
bugsnag.Notify(err error, rawData... interface{})
```
to
```go
bugsnag.Notify(rawData... interface{})
```
wouldn't break directly for users who just call this function as-is, it would be breaking in the case that users decide to create a type alias for the function signature of our client, in order to facilitate testing or passing the function outside packages or libraries.
Also added a test to gain some more confidence that `notifier.NotifySync` allows you to override the async default, and that this state won't …
> Revert notify signature

- bugsnag.go
- sessions/config.go
- sessions/config_test.go
- sessions/publisher.go
- sessions/publisher_test.go
We were previously still sending sessions if the release stage was outside a defined set of acceptable notify release stages. This PR fixes that.
> [fix] Make NotifyReleaseStages apply to sessions

- configuration.go
- configuration_test.go
In particular, ensure that if the release stage is empty, it *will* send
the report.
In all fairness the fact that this has to be done through creating a
manual `bugsnag.Configuration` struct instead of using
`bugsnag.Configure` means that this is unlikely to cause confusion.
This is now consistent with other notifiers and how we treat
notify release stages for sessions.
Also made the test format for this a bit more consistent with most of the tests in the library.
> [fix] Make notify release stages consistent

- bugsnag_test.go
- features/fixtures/app/main.go
- features/plain_features/multieventsession.feature
- panicwrap_test.go
- payload.go
- report.go
- sessions/session.go
- sessions/tracker.go
- sessions/tracker_test.go
Ensure that multiple crashes in the same session only counts towards the stability score once by keeping track of how many events have been reported against a single session.
We can count how many handled/unhandled events have happened already through a count in the session struct itself. This was basically identical to the already existing `eventCountsJSON` struct, so I just moved that into the `sessions` package, and changed the references to use that.
> Dedupe crash count in session

- negroni/bugsnagnegroni.go
- negroni/negroni_test.go
Ensures that session tracking and correct configuration is applied as expected when only doing a `bugsnagnegroni.AutoNotify()` without a `bugsnag.Configure()` first, in accordance with our documentation.
Additionally improves the go tests to include a test case for handled events.
> Session tracking negroni fixes

- .travis.yml
Disable testing of branch and PR builds against Go's latest development
branch. This should be done on a scheduled basis instead, but this
is too strict to prevent PR builds and branch builds from passing.
> Don't test against Go's master

- sessions/tracker.go
Make this package compile on Windows.
There was a call to `syscall.Getpid()` which does not exist on Windows. Change this to instead use `os.FindProcess(os.Getpid())`.
I have verified manually that sessions and handled & unhandled events get sent to Bugsnag by trying out the example projects.
Fixes #96
> Fix Windows compilation issue

- request_extractor.go
- request_extractor_test.go
Make sure that all data sanitization using `Config.ParamsFilters` behaves the same. the `ParamsFilters` slice should contain "sensitive substrings", so if a key contains any of the `ParamsFilters`, it should be considered sensitive.
This is already the case in the metadata sanitizer:
https://github.com/bugsnag/bugsnag-go/blob/834d8fee64233ea79b0389ad7a5a438261788f66/metadata.go#L185-L192
Why was this approach to the goal used?
Use the same `string.Contains` logic also for request headers. Makes sure to filter heades like `Set-Cookie` or `X-Service-Secret`.
Changed `request_extractor.contains`.
Updated the corresponding test case.
> Sanitize request headers like other metadata fields

- .travis.yml
- CHANGELOG.md
- request_extractor.go
- request_extractor_test.go
- sessions/tracker.go
Fix compilation error on Windows. Windows users can now compile projects with the 1.4.x releases of bugsnag-go.
This fix is a considerable net positive as it fixes the compilation error on Windows. However, the caveat to that is that interrupts are now swallowed (on Windows only) as programmatically sending interrupts on Windows is not implemented in the Go standard library. This means that users might have to interrupt their application twice in order to trigger an interrupt.
> Release v1.4.1

- bugsnag_test.go
- event.go
- features/fixtures/app/main.go
- features/fixtures/docker-compose.yml
- features/fixtures/gin/main.go
- features/fixtures/martini/main.go
- features/fixtures/negroni/main.go
- features/fixtures/net_http/main.go
- features/fixtures/revel/app/controllers/app.go
- features/gin_features/handled.feature
- features/martini_features/handled.feature
- features/negroni_features/handled.feature
- features/net_http_features/handled.feature
- features/plain_features/handled.feature
- features/revel_features/handled.feature
In v1.4.0 we introduced a bug when changing the order of the error and
other metadata in notifier.Notify. This commit rectifies this by
explicitly checking that the error class has not been set previously
before setting it automatically.
- Check to see if the error class has already been set before assigning the default error class from the error itself.
- Notify test to catch this bug if it should occur in future releases.
Fixes #98 
@Cawllec could you have a look and see if you think we need another set of maze tests for this case?
> Ensure user-specified error classes take priority

- .travis.yml
- Makefile
We currently pull down the latest versions of all our dependencies, including Gin, before attempting to run our tests. Gin has recently dropped their support for Go 1.7, and we therefore have to ignore the Gin tests when running CI against Go 1.7.
Additionally silence comments in Makefile
Related to #117 as this PR is blocked by a failing build which this aims to solve.
> [chore] Drop Go 1.7 x Gin (latest) unit test combo

- bugsnag.go
- request_extractor.go
- request_extractor_test.go
Currently, when the Bugsnag client extracts the URL from the request, it includes the full query parameters, without any filtering/redaction. This will leak any sensitive keys sent as query parameters, like access tokens.
This PR changes that so that we go through each query parameter and filter out sensitive ones (similar to how we do for request headers).
This PR also adds `access_token` as a default sensitive parameter, since it's very unlikely users want to include those in Bugsnag reports.
`extractRequestInfoFromReq`
I've added tests for the function.
One drawback of this change is that the URL query parameters sent to Bugsnag will no longer be in the order that the client sent them, but sorted alphabetically by key. This is because `url.ParseQuery` returns a (type-aliased) …
> Redact request url

- .travis.yml
- Makefile
Gin has dropped support for these versions in its latest release, [blocking the runtime versions work](https://travis-ci.com/bugsnag/bugsnag-go/builds/117849485).
This is an extension of #118
> Don't run builds against Gin + Go 1.8/1.9

- .travis.yml
- Makefile
- device/runtimeversions.go
- device/runtimeversions_test.go
- examples/revelapp/README.md
- gin/bugsnaggin.go
- martini/bugsnagmiddleware.go
- negroni/bugsnagnegroni.go
- payload.go
- payload_test.go
- report.go
- revel/bugsnagrevel.go
- sessions/integration_test.go
- sessions/payload.go
Introduce runtime version data to the report and session payloads.
```
device.RuntimeVersions
device.GetRuntimeVersions()
device.AddVersion
```
- Session and report payloads.
- Revel example README (fix typo)
- Introduced OS Name in report payload as well (already existed in session payload)
Added some unit tests, and verified that the payloads show up as expected, including the new runtime version data.
It's unfortunate that we're using a global variable for the runtime versions, but this cached value simplifies things a lot, and is relatively harmless in this package. If/when we decide to upgrade to a v2 we should get rid of all global state anyway.
#121 is the first commit on this branch in order to get a passing build.
- This pull request is …
> Runtime versions

- .travis.yml
- CHANGELOG.md
- Makefile
- bugsnag.go
- device/runtimeversions.go
- device/runtimeversions_test.go
- examples/revelapp/README.md
- gin/bugsnaggin.go
- martini/bugsnagmiddleware.go
- negroni/bugsnagnegroni.go
- payload.go
- payload_test.go
- report.go
- revel/bugsnagrevel.go
- sessions/integration_test.go
- sessions/payload.go
This release adds runtime version data to the report and session payloads, which will show up under the Device tab in the Bugsnag dashboard.
* Ignore Gin unit tests when running against the latest version of Gin on Go versions below 1.10 as Gin has dropped support for these versions.
[#121](https://github.com/bugsnag/bugsnag-go/pull/121)
* Introduce runtime version data to the report and session payloads. Additionally adds the OS name to reports.
[#122](https://github.com/bugsnag/bugsnag-go/pull/122)
> Release v1.5.3

- CHANGELOG.md
- errors/error.go
- errors/error_test.go
- errors/stackframe.go
Use [`runtime.CallersFrames`](https://golang.org/pkg/runtime/#CallersFrames) to unwind stack traces, taking into account any inlined frames (thus producing a more accurate trace).
Closes #114 
This is a trimmed down version of #114, avoiding changing public function signatures (for now) and avoiding pulling in `pkg/errors` (which will added to support the `pkg/errors` stacktrace format in a subsequent PR).
* Add a (private) `function` field to `StackFrame`. This caches the [`Func`](https://golang.org/pkg/runtime/#Func) value rather than using [`FuncForPC`](https://golang.org/pkg/runtime/#Func).
* Construct the stack by iterating over the frames returned by `runtime.CallersFrames` using the error `stack` value as input.
* Updated the error tests to assert expected stack trace frames …
> fix: use runtime.callersframes to handle inlined frames

- notifier_test.go
- panicwrap_test.go
Make stack-asserting tests more specific and ignore platform-specific lines. Resolves issue with tests which fail on master.
> tests: Assert expected file names/line numbers rather than counts

- CHANGELOG.md
- features/gin_features/autonotify.feature
- features/martini_features/autonotify.feature
- features/negroni_features/autonotify.feature
- features/revel_features/autonotify.feature
- payload.go
- payload_test.go
- report.go
Framework was missing from handled state payload contents. Updated the JSON serializer to include it and the tests to validate the change. Handled events already included assertions to ensure the handled state was sent correctly.
* Added new assertions for setting the framework value to the payload and web framework tests.
* Tested manually to ensure a custom handled state with a framework value was reflected correctly on the dashboard
> fix: send framework name with severity reason

- CHANGELOG.md
- errors/error.go
- errors/error_test.go
Support reporting stack traces captured using the [`pkg/errors`](https://github.com/pkg/errors) package instead of generating a new stack when `Notify()` is called.
Closes #128 - updates the premise to use the latest pre-release  branch and avoids adding go module files, which will be handled in a dedicated changeset.
Create a new interface for objects implementing `StackTrace()`, returning an [`errors.StackTrace`](https://godoc.org/github.com/pkg/errors#StackTrace) instance (which is an array of `uintptr` representing program counters). Given the array of program counters, the error can be processed normally.
* Added `errorWithStack` to represent the new error type (the `errors` package does not export this interface but it is listed as stable)
* Added a new test for wrapping an `error` …
> feat(errors): extract pkg/errors stacktraces

- .github/workflows/test-package.yml
Check out the source of the repository into a configured `$GOPATH`, instead of an arbitrary directory. This avoids situations where there might be a second copy on disk (and on a different branch) which might be referenced by subpackages or otherwise cause confusion.
> ci: configure gopath, check out source into path

- CHANGELOG.md
- bugsnag_test.go
- event.go
- features/fixtures/app/main.go
- features/plain_features/handled.feature
- features/steps/go_steps.rb
- notifier_test.go
- payload_test.go
- report.go
Support passing a function to `Notify()` to allow modification of the complete event, including the stacktrace, on a per-invocation basis.
```go
bugsnag.Notify(err, func(event *bugsnag.Event) {
event.Context = fmt.Printf("logger: %v", err)
})
```
Check for a function argument to `Notify()`, aggregating any found into a list which is called once the error is constructed. Like other arguments to `Notify()`, subsequent arguments can override previous ones, which is why the callbacks are stored as a collection rather than overriding a single instance.
The `StackFrame` structure is now public to support checking against or modifying stack frame contents. There's an example in the changelog for a common case: trimming stacktraces for functions routed through a logger or common error delivery …
> feat: Support modifying events within a callback function

- .github/workflows/test-package.yml
- CHANGELOG.md
- bugsnag.go
- bugsnag_test.go
- errors/error.go
- errors/error_test.go
- event.go
- features/fixtures/app/main.go
- features/gin_features/autonotify.feature
- features/martini_features/autonotify.feature
- features/negroni_features/autonotify.feature
- features/plain_features/handled.feature
- features/revel_features/autonotify.feature
- features/steps/go_steps.rb
- notifier_test.go
- payload.go
- payload_test.go
- report.go
* Extract stacktrace contents on errors wrapped by [`pkg/errors`](https://github.com/pkg/errors).
[#144](https://github.com/bugsnag/bugsnag-go/pull/144)
* Support modifying an individual event using a callback function argument.
```go
bugsnag.Notify(err, func(event *bugsnag.Event) {
event.ErrorClass = "Unexpected Termination"
event.MetaData.Update(loadJobData())
if event.Stacktrace[0].File = "mylogger.go" {
event.Stacktrace = event.Stacktrace[1:]
}
})
```
The stack trace of an event is now mutable so frames can be removed or modified.
[#146](https://github.com/bugsnag/bugsnag-go/pull/146)
* Send web framework name with severity reason if set. Previously this value was ignored, obscuring the severity reason for failed web requests captured by bugsnag middleware. …
> Release v1.6.0

- CHANGELOG.md
- event.go
- features/fixtures/app/main.go
- features/plain_features/handled.feature
- notifier_test.go
- payload.go
- payload_test.go
- report.go
* Add `Unhandled` property to event. The default value is the `Unhandled`	value of `handledState`, which is otherwise immutable. This allows for tracking when the value has been changed (assuming that if one callback changes the value, and another changes it back, the change didn't matter).
* Tested manually to verify dashboard appearance as well as adding new automated tests to ensure `unhandledOverridden` is only sent when true.
> feat: support modifying handled-ness in callbacks

- CHANGELOG.md
- bugsnag.go
- event.go
- features/fixtures/app/main.go
- features/plain_features/handled.feature
- notifier_test.go
- payload.go
- payload_test.go
- report.go
* Support for changing the handled-ness of an event prior to delivery. This
allows for otherwise handled events to affect a project's stability score.
```go
bugsnag.Notify(err, func(event *bugsnag.Event) {
event.Unhandled = true
})
```
> Release v1.7.0

- CHANGELOG.md
- errors/error.go
- errors/error_test.go
- event.go
- features/fixtures/app/main.go
- features/plain_features/handled.feature
- payload.go
Including the contents of errors which are wrapped by later errors. When a new error is generated from an earlier error to add additional context, the nested error (and associated message and/or stack trace contents) is lost. This change attempts to fix this by attaching each unwrapped error as a cause.
Any reported error which implements the following interface:
```go
type errorWithCause interface {
Cause() error
}
```
will have the cause included as a previous error in the resulting event. The cause information will be available on the Bugsnag dashboard and is available for inspection in callbacks on the `errors.Error` object.
Given the following error implementation:
<details>
<summary>Example error implementation</summary>
```go
package main
import (
"runtime"
)
type customErr struct …
```
> feat: Support unwrapping causes from errors

- CHANGELOG.md
- bugsnag.go
- errors/error.go
- errors/error_test.go
- event.go
- features/fixtures/app/main.go
- features/plain_features/handled.feature
- payload.go
- payload_test.go
* Support unwrapping the underlying causes from an error, including attached stack trace contents if available.
Any reported error which implements the following interface:
```go
type errorWithCause interface {
Unwrap() error
}
```
will have the cause included as a previous error in the resulting event. The cause information will be available on the Bugsnag dashboard and is available for inspection in callbacks on the `errors.Error` object.
```go
bugsnag.OnBeforeNotify(func(event *bugsnag.Event, config *bugsnag.Configuration) error {
if event.Error.Cause != nil {
fmt.Printf("This error was caused by %v", event.Error.Cause.Error())
}
return nil
})
```
> release v1.8.0

- features/fixtures/app/Dockerfile
- features/fixtures/app/main.go
- features/fixtures/app/run.sh
- features/plain_features/endpoint.feature
- features/plain_features/handled.feature
- features/plain_features/multieventsession.feature
- features/plain_features/panics.feature
- features/plain_features/sessioncontext.feature
- features/plain_features/synchronous.feature
- features/steps/go_steps.rb
Add regression test coverage for crucial component of the library, adding a scaffold for some improvements coming in this area.
Probably easiest to see each commit:
* The first to remove spaces was to make the new scripts run easier without dealing with adding escaping logic in a few places.
* The second adds a run script to the test environment so that when the process crashes, there is time for the remaining event to be sent. This script is similar to ones in production environments, where otherwise the process won't be able to be properly monitored (since in go crash info is only present in stdout/err and not passed to handlers).
The test case itself is simple with two variations in error message depending on the go version.
> add integration test for unrecovered panic

- CHANGELOG.md
- errors/error.go
- errors/parse_panic.go
- errors/parse_panic_test.go
Support parsing "fatal error"-style panics from go, such as from concurrent map read/writes, out of memory errors, and nil goroutines.
In the event of an unrecoverable error, the go runtime invokes [`fatalpanic`](https://github.com/golang/go/blob/2517f4946b42b8deedb864c884f1b41311d45850/src/runtime/panic.go#L1185). These errors terminate the process with a message matching ["fatal error: [cause]"](https://github.com/golang/go/blob/2517f4946b42b8deedb864c884f1b41311d45850/src/runtime/panic.go#L1106). This changeset updates the parser to look for the "fatal error:" component to begin parsing the rest of the goroutine contents as a crash.
Updated the go process output parser to detect panics which begin with "fatal error". Some errors terminate the process without the more common "panic" …
> feat: capture 'fatal error' crashes as panics

- CHANGELOG.md
- bugsnag.go
- errors/error.go
- errors/parse_panic.go
- errors/parse_panic_test.go
- features/fixtures/app/Dockerfile
- features/fixtures/app/main.go
- features/fixtures/app/run.sh
- features/plain_features/endpoint.feature
- features/plain_features/handled.feature
- features/plain_features/multieventsession.feature
- features/plain_features/panics.feature
- features/plain_features/sessioncontext.feature
- features/plain_features/synchronous.feature
- features/steps/go_steps.rb
- payload_test.go
* Support capturing "fatal error"-style panics from go, such as from concurrent map read/writes, out of memory errors, and nil goroutines.
> release v1.9.0

- v2/go.mod
- v2/go.sum
- v2/panicwrap_test.go
Unneeded on go1.8+ (and the baseline for v2 is go1.11+)
> build: remove dependency on osext

- CHANGELOG.md
- features/configuration.feature
- features/fixtures/autoconfigure/Dockerfile
- features/fixtures/autoconfigure/cases.go
- features/fixtures/autoconfigure/main.go
- features/fixtures/autoconfigure/run.sh
- features/fixtures/docker-compose.yml
- features/steps/go_steps.rb
- v2/bugsnag.go
- v2/configuration.go
Read `BUGSNAG_*` environment variables and configure the library automatically.
* For string-based properties, variables are accepted as-is. For example, the value of `BUGSNAG_API_KEY`, if set, is applied to `Configuration.APIKey`.
* For slice of string properties, commas are supported as a delimiter. Set `BUGSNAG_PROJECT_PACKAGES` to `main,example.com/repo` to mark code from the `main` and `example.com/repo` packages as in-project.
* For boolean properties, variables are checked against the string value `1`, and, if not empty string, are set to true if equal or false if not.
Added new integration tests for each supported variable
> Support configuring the library through environment variables

- CHANGELOG.md
- UPGRADING.md
- features/endpoint.feature
- features/fixtures/app/main.go
- features/handled.feature
- v2/configuration.go
- v2/configuration_test.go
`Endpoint` has been deprecated for some time, removing it as a part of the major release.
> Remove deprecated config

- UPGRADING.md
- v2/bugsnag.go
- v2/bugsnag_test.go
- v2/payload.go
- v2/payload_test.go
- v2/sessions/integration_test.go
Replaces `VERSION` with `Version` to be better aligned with Go naming conventions.
> Rename constant to match platform idioms

- .github/workflows/test-package.yml
- CHANGELOG.md
- v2/configuration.go
- v2/configuration_test.go
- v2/panicwrap_test.go
- v2/sessions/integration_test.go
Fix a bug on windows where build/run paths are not correctly stripped depending on which path separators are used. Go itself always returns file paths using `/` as the separator, though the `GOPATH` environment variable (and/or `GOROOT()`) may use `\` depending on a system's settings.
* Added a check when a configuration is updated to swap path separators on windows if needed
* Updated the existing unit suite to run on windows on CI
* Tested the change manually:
Before:
After:
> fix(config): ensure correct path separator used on windows

- CHANGELOG.md
- features/configuration.feature
- features/fixtures/docker-compose.yml
- v2/configuration.go
- v2/env_metadata.go
- v2/env_metadata_test.go
- v2/environment.go
- v2/environment_test.go
Support "no code" metadata collection by automatically collecting content from the environment with a bugsnag prefix.
🗒️ Largely reviewed previously as a part of #155 (https://github.com/bugsnag/bugsnag-go/pull/155#discussion_r555643621, https://github.com/bugsnag/bugsnag-go/pull/155#discussion_r558238333), with suggested adjustments
The environment variable name after the prefix is expected to be the tab and key name, optionally delimited by an underscore.
Examples:
```bash
BUGSNAG_METADATA_device_KubePod="carrot-delivery-service-beta1 reg3"
BUGSNAG_METADATA_device_deployment_area=region5_1
BUGSNAG_METADATA_carrier=proof
```
```json
{
"metaData": {
"device": {
"KubePod": "carrot-delivery-service-beta1 reg3",
"deployment_area": "region5_1"
},
"custom": { "carrier": "proof" }
}
}
```
* …
> Support appending metadata through environment variables

- .github/workflows/test-package.yml
- CHANGELOG.md
- features/configuration.feature
- features/fixtures/docker-compose.yml
- v2/bugsnag.go
- v2/configuration.go
- v2/configuration_test.go
- v2/env_metadata.go
- v2/env_metadata_test.go
- v2/environment.go
- v2/environment_test.go
- v2/panicwrap_test.go
- v2/sessions/integration_test.go
* Support appending metadata through environment variables prefixed with
`BUGSNAG_METADATA_`
* Fix `GOPATH`, `SourceRoot` and project package path stripping from stack
traces on Windows by using the correct path separators.
> release v2.1.0

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/support.md
Bringing templates inline with our base config, to match other Go repos & fix typo. I have left Integration frameworks in the issue report template in case users raise issue in this repo rather than the specific framework repos
> docs(templates): fix the issue report & PR templates

- sessions/integration_test.go
Stop failed ubuntu autopkgtests
Use the timeout from v2
increase the sleep duration
tested in ubuntu autopkgtest environment using existing tests.
These tests were failing in the Ubuntu autopkgtest environment. We are not on version 2 yet, so this change is relevant to Ubuntu.
> increase sleep to prevent failed tests

- .github/workflows/test-package.yml
- features/fixtures/app/Dockerfile
- features/fixtures/autoconfigure/Dockerfile
- features/fixtures/net_http/Dockerfile
- features/handled.feature
- features/net-http/handled.feature
- features/steps/go_steps.rb
- features/support/env.rb
The existing setup is dependent on `GO111MODULE=auto`, which will cease to work in [go1.17](https://blog.golang.org/go116-module-changes).
This change instead builds within the module-aware directories and adds mod files to test apps during the run.
Tidied up a test case along the way.
> Update CI to run without legacy module config

- CHANGELOG.md
- v2/go.mod
- v2/go.sum
https://github.com/bugsnag/panicwrap/releases/tag/v1.3.4 introduces fixes for building on linux & darwin on arm64. This PR bumps the version used by `bugsnag-go` to utilize this release.
Closes #179 
Version change to `go.mod` & `go.sum` following `$ go get .`.
> update(panicwrap): bump panicwrap version to v1.3.4

- .github/workflows/license-audit.yml
- CHANGELOG.md
- v2/bugsnag.go
- v2/go.mod
- v2/go.sum
Update `bugsnag-go` to include changes from `next` branch.
* Update panicwrap dependency to v1.3.4 which fixes build support for linux & darwin arm64.
* Push licence auditor workflow changes from `next` branch.
New version of `panicwrap` release was tested separately in https://github.com/bugsnag/panicwrap/releases/tag/v1.3.4
> Release v2.1.2

- report.go
- sessions/publisher_test.go
- sessions/session.go
- v2/go.mod
- v2/go.sum
- v2/report.go
- v2/sessions/publisher_test.go
- v2/sessions/session.go
Replaces the gofrs uuid package as it broke support for old versions of go in a recent commit and has no mechanism for version control
All behavior should be preserved, and go 1.11 and 1.12 tests pass again
> refactor: use google uuid package

- v2/configuration.go
`**` is supported by https://github.com/bugsnag/bugsnag-go/pull/25, but comments are not updated. So I updated the comment.
> doc: Show ProjectPackages supports double star glob

- .github/workflows/test-package.yml
- features/fixtures/app/Dockerfile
- features/fixtures/app/main.go
- features/fixtures/autoconfigure/Dockerfile
- features/fixtures/net_http/Dockerfile
Update test matrix to include latest versions of Go.
Make sure building with the latest versions of Go is successful and monitor how long it takes to build.
Added latest Go versions, `v1.17 - v1.22`, to test-matrix. 
Updated the `unhandledCrash()` function in `main.go` with `noinline` to accommodate the inline function behavior introduced in `v1.17+`.
Updated the `RUN` commands in all Dockerfile(s) to a conditional to use `go get` or `go install` dependent on the version of Go being used.
Moved `ARG GO_VERSION` up to allow consumption by `RUN` command.
Relying on testing via CI.
> Updated test matrix to latest go versions.

- CHANGELOG.md
- middleware.go
- v2/middleware.go
- v2/middleware_test.go
One of the two default OnBeforeNotify callbacks was panicking if http request in Event's RawData was nil.
Check for nil request added (https://github.com/bugsnag/bugsnag-go/pull/210).
-
Added check for nil http.Request in `httpRequestMiddleware` callback.
Added unit tests for nil request scenario.
> Fix middleware panic on nil *http.Request

- v2/errors/error.go
- v2/errors/error_test.go
- v2/errors/error_types_test.go
Prepare examples in form of unit tests for checking every possible error type's stack.
-
Added documentation on why we don't change uintptr representation of stack frame.
Added `v2/errors/error_types_test.go` file.
> Add unit tests for different error types' stacks

- CHANGELOG.md
- v2/metadata.go
- v2/metadata_test.go
New fields with complex struct types in metadata could not be properly processed and resulted in "{}" in output.
-
Added handling for known complex types like date and time, errors, stringers.
Unit tests added.
> Handle complex structs in metadata

- CHANGELOG.md
- event.go
- features/fixtures/app/main.go
- features/fixtures/docker-compose.yml
- features/handled.feature
- features/net-http/handled.feature
- features/plain_features/panics.feature
- v2/configuration.go
- v2/event.go
In case of different main files it's impossible to differentiate which main file the error came from.
It's less invasive than correcting the order of trimming paths. (#211)
First trimming is performed for every package and it trims everything until the package name.
It's mostly for external packages or golang internal pkg.
Because `main` is a special package (pkg name is just "main" without module) we omit it in the first trimming.
Then if it's added to ProjectPackages and SourceRoot is properly configured the path will be trimmed properly.
So for input path: "/user/name/work/cmd/main.go"
current solution will provide: "main.go"
and this PR's solution will provide either "/user/name/work/cmd/main.go" or "cmd/main.go" depending of whether SourceRoot is configured.
Skipped trimming path for …
> Stop trimming everything before "main.go" on main packages

- v2/sessions/tracker_test.go
Session counting test was flaky - probably did not wait for all the sessions to be consumed.
-
Increased wait duration after sessions were created so they can be all consumed by `st.processSessions` thread.
Unit tests for session tracker changed.
> Fix session tracking test - wait for all sessions to be processed

- CHANGELOG.md
- middleware.go
- v2/bugsnag.go
- v2/middleware.go
- v2/middleware_test.go
> Merge 'master' into 'next'

- CHANGELOG.md
- v2/metadata.go
- v2/metadata_test.go
When we pass a pointer to complex interface (that in Sanitizer gets caught in type switch-case) we don't check if the pointer is nil.
Type specific switch-case tried to check for interface function `String()` for `fmt.Stringer` interface on the nil pointer leading to a panic.
Moved check for nil pointers and interfaces before any other type matching is done.
In `metadata.AddStruct` used an actual sanitized value to pass into `metadata.Add`.
New tests for adding pointers with Stringer interface to metadata - either nil ptr or normal.
> Handle empty pointers to complex structs in metadata.Add

- v2/metadata.go
- v2/metadata_test.go
We log in json, and send details and types to both our logger and also to bugsnag that are json.RawMessage, have a MarshalJSON method, or are byte slices.
Good place for it.
See PR.
Added test cases to cover the new functionality.
> Sanitize should also handler json and []byte

- CHANGELOG.md
- v2/bugsnag.go
* Sanitize for metadata should also handler json and []byte
[#226](https://github.com/bugsnag/bugsnag-go/pull/226)
[Chris Duncan](https://github.com/veqryn)
> Update version to 2.4.0

- CHANGELOG.md
- LOCAL_TESTING.md
- features/fixtures/app/Dockerfile
- features/fixtures/app/main.go
- features/fixtures/autoconfigure/Dockerfile
- features/fixtures/net_http/Dockerfile
- features/fixtures/net_http/main.go
- features/handled.feature
- v2/bugsnag_test.go
- v2/configuration.go
- v2/notifier.go
- v2/report_publisher.go
In case of heavy load notifier created too many goroutines for sending events thus consuming a lot of resources.
Adding a single goroutine with a channel will limit usage of resources and allow events to get queued to be sent instead of trying to send everything at once.
Added a single goroutine as a default strategy for the async delivery. On failure events are dropped.
Goroutine has two ways of handling graceful shutdown. Either react to a signal which it's registered to or react to main program context sending `Done()`.
Added configuration option for passing MainProgramContext.
Existing maze-runner tests can be used
> Change async event delivery to single goroutine with events channel queue

- .github/workflows/test-package.yml
Pin tests to Ubuntu 20.04.
GitHub Actions recently updated `ubuntu-latest` to 22.04, which for some reason breaks the fixture build.  This PR gets us moving again while we look into that.
Covered by CI.
> Pin tests to Ubuntu 20.04

- features/fixtures/app/Dockerfile
- features/fixtures/app/command.go
- features/fixtures/app/main.go
- features/fixtures/docker-compose.yml
- features/steps/go_steps.rb
- features/support/env.rb
- v2/headers/prefixed.go
- v2/headers/prefixed_test.go
- v2/payload.go
- v2/sessions/publisher.go
Prepared test app's command pattern.
Integrity header added to event and session payload.
In test app main file I've left "scenario"-like functions - they will be changed in the next PR.
> Add integrity header, change to command pattern in test app

- features/fixtures/app/autoconfig_scenario.go
- features/fixtures/app/handled_scenario.go
- features/fixtures/app/main.go
- features/fixtures/app/metadata_scenario.go
- features/fixtures/app/nethttp_scenario.go
- features/fixtures/app/panic_scenario.go
- features/fixtures/app/session_scenario.go
- features/fixtures/app/unhandled_scenario.go
- features/fixtures/app/user_scenario.go
- features/fixtures/app/utils.go
Test cases from autoconfig test app moved into autoconfig_scenario.
Same for nethttp app - it's moved to nethttp_scenario.
Those test apps will be removed later.
> Separate test functions into scenarios

- features/support/env.rb
- v2/headers/prefixed.go
- v2/headers/prefixed_test.go
- v2/payload.go
- v2/sessions/publisher.go
Server side notifiers don't have to support Bugsnag-Integrity header.
Disabled the check from maze-runner side.
> Remove Bugsnag-Integrity header

- Gemfile
- features/net-http/appversion.feature
- features/sessioncontext.feature
- features/support/env.rb
Adds custom error & session validation to be run on every scenario, replacing steps already in use.
Also demonstrates use of configured validation
> Adds custom error validation

- v2/bugsnag.go
- v2/bugsnag_test.go
- v2/report_publisher.go
Customers reported that delivery goroutine that starts as soon as module is loading is appearing as a leak in the diagnostic tools such as `goleak`. It can be safely moved to `Configure` method.
In the delivery goroutine we were also subscribing to os signals as a way to provide graceful shutdown. Unfortunately that led to main program being unable to capture signals. So our `signal.Notify` usage has to be removed.
Fixes issues:
- https://github.com/bugsnag/bugsnag-go/issues/247
- https://github.com/bugsnag/bugsnag-go/issues/249
Removed `signal.Notify` usage in delivery goroutine.
Moved starting delivery goroutine to `Configure` method.
Tested using code snippets provided in issues.
> Move start of delivery goroutine to configure, don't wait on signals in delivery

- CHANGELOG.md
- v2/bugsnag.go
* Move start of delivery goroutine to configure, don't wait on signals in delivery
[#250](https://github.com/bugsnag/bugsnag-go/pull/250)
> Update version to 2.5.1

- CHANGELOG.md
- v2/bugsnag.go
* Set default endpoints based on API key [#259](https://github.com/bugsnag/bugsnag-go/pull/259)
> Update version to 2.6.0

- CHANGELOG.md
- v2/configuration.go
- v2/configuration_test.go
If user provided Endpoints configuration only by Environment variables in the current solution they would still be overwritten by defaults.
If the endpoint value is already set and the next config does not specify it - then do not update the value with default.
Added unit tests that set environment variables.
> Handle endpoints being set only in env vars
